NLP



In [ ]:
text ='HELLO MY NAME IS BUNNY AND I AM STUDYING IN AIML IN KSRM'
text_lower = text.lower()
print(text_lower)

hello my name is bunny and i am studying in aiml in ksrm


In [ ]:
import re
text ='HELLO! MY NAME IS BUnny AND i AM STUDYING IN AIML IN KSRM'
text_clean = re.sub(r'[a-z]','07',text)
print(text_clean)


HELLO! MY NAME IS BU070707 AND 07 AM STUDYING IN AIML IN KSRM


In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords',quiet=True)
stop_words = set(stopwords.words('english'))
text = ' hello my name is bunny and i am studying in aiml'
tokens = []
for word in text.split():
  if word not in stop_words:
    tokens.append(word)
print(tokens)

['hello', 'name', 'bunny', 'studying', 'aiml']


In [ ]:
import nltk
nltk.download('punkt_tab',quiet=True)
basic = text.split()
print('Basic split:',basic)
from nltk.tokenize import word_tokenize
smart = word_tokenize(text.lower())
print('NLTK tokenise:',smart)

Basic split: ['hello', 'my', 'name', 'is', 'bunny', 'and', 'i', 'am', 'studying', 'in', 'aiml']
NLTK tokenise: ['hello', 'my', 'name', 'is', 'bunny', 'and', 'i', 'am', 'studying', 'in', 'aiml']


In [ ]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('wordnet', quiet=True)

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

words = ['running', 'studies', 'better', 'caring', 'happily']

for word in words:
    stem = stemmer.stem(word)
    lemma = lemmatizer.lemmatize(word, pos='v')

    print(f'{word:12} | stem: {stem:10} | lemma: {lemma}')

running      | stem: run        | lemma: run
studies      | stem: studi      | lemma: study
better       | stem: better     | lemma: better
caring       | stem: care       | lemma: care
happily      | stem: happili    | lemma: happily


In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download(['stopwords','wordnet','punkt'],quiet=True)
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

def preprocess(text):
  text=text.lower()
  text=re.sub(r'[^a-zA-Z]',' ',text)
  tokens =text.split()
  filtered_tokens=[]
  for w in tokens:
    if w not in stop_words:
      filtered_tokens.append(w)
  lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]

  return ' '.join(lemmatized_tokens)
sample_text = 'i am going to running the some one story'
processed_text = preprocess(sample_text)
print(f"Original: {sample_text}\nProcessed: {processed_text}")



Original: i am going to running the some one story
Processed: going running one story


In [2]:
from sklearn.feature_extraction.text import CountVectorizer
emails= [
    'circket match circket match circket match',
    'free win money free win money win',
    'cricket match free win money cricket',
]
cv = CountVectorizer()
X = cv.fit_transform(emails).toarray()
print('vocabulary:',cv.get_feature_names_out())
print('boW matrix:')
print(X)

vocabulary: ['circket' 'cricket' 'free' 'match' 'money' 'win']
boW matrix:
[[3 0 0 3 0 0]
 [0 0 2 0 2 3]
 [0 2 1 1 1 1]]


In [4]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import numpy as np
emails= [
    'circket match circket match circket match',
    'free win money free win money win',
    'cricket match free win money cricket',
]
tfidf = TfidfVectorizer(sublinear_tf=True, max_df=0.95,min_df=1)
X = tfidf.fit_transform(emails).toarray()
print('vocabulary:',tfidf.get_feature_names_out())
print('TF-IDf matrix(rounded):')
print(np.round(X,3))

vocabulary: ['circket' 'cricket' 'free' 'match' 'money' 'win']
TF-IDf matrix(rounded):
[[0.796 0.    0.    0.605 0.    0.   ]
 [0.    0.    0.532 0.    0.532 0.659]
 [0.    0.744 0.334 0.334 0.334 0.334]]
